/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import java.awt.Color;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/**
 *
 * @author Jossi
 */
public class Calculadora extends javax.swing.JFrame {

    
    ScriptEngineManager jv= new ScriptEngineManager();
    ScriptEngine jvs = jv.getEngineByName("JavaScript");
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDivision = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnParentesisdos = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnparentesisuno = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        jButton5.setBackground(new java.awt.Color(72, 201, 176));
        jButton5.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(72, 201, 176));
        jButton5.setText("C");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 253, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperacion.setBackground(new java.awt.Color(174, 214, 241));
        txtOperacion.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(52, 73, 94));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 438, 68));

        txtResultado.setBackground(new java.awt.Color(174, 214, 241));
        txtResultado.setFont(new java.awt.Font("Rod", 1, 48)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(52, 73, 94));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 438, 104));

        jButton1.setBackground(new java.awt.Color(46, 64, 83));
        jButton1.setForeground(new java.awt.Color(46, 64, 83));
        jButton1.setText("Oscuro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(46, 64, 83));
        jButton2.setForeground(new java.awt.Color(46, 64, 83));
        jButton2.setText("Claro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDivision.setBackground(new java.awt.Color(72, 201, 176));
        btnDivision.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(72, 201, 176));
        btnDivision.setText("/");
        btnDivision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel2.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, 80));

        btnIgual.setBackground(new java.awt.Color(51, 51, 255));
        btnIgual.setFont(new java.awt.Font("Rod", 1, 48)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(72, 201, 176));
        btnIgual.setText("=");
        btnIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel2.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 100, 70));

        btnParentesisdos.setBackground(new java.awt.Color(72, 201, 176));
        btnParentesisdos.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnParentesisdos.setForeground(new java.awt.Color(72, 201, 176));
        btnParentesisdos.setText(")");
        btnParentesisdos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnParentesisdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesisdosActionPerformed(evt);
            }
        });
        jPanel2.add(btnParentesisdos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 80));

        btnPorcentaje.setBackground(new java.awt.Color(72, 201, 176));
        btnPorcentaje.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnPorcentaje.setForeground(new java.awt.Color(72, 201, 176));
        btnPorcentaje.setText("%");
        btnPorcentaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });
        jPanel2.add(btnPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 90, 70));

        btnPunto.setBackground(new java.awt.Color(72, 201, 176));
        btnPunto.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(72, 201, 176));
        btnPunto.setText(".");
        btnPunto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, 70));

        btnMultiplicacion.setBackground(new java.awt.Color(72, 201, 176));
        btnMultiplicacion.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnMultiplicacion.setForeground(new java.awt.Color(72, 201, 176));
        btnMultiplicacion.setText("X");
        btnMultiplicacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 100, 80));

        btnSuma.setBackground(new java.awt.Color(72, 201, 176));
        btnSuma.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(72, 201, 176));
        btnSuma.setText("+");
        btnSuma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 100, 70));

        btnMenos.setBackground(new java.awt.Color(72, 201, 176));
        btnMenos.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(72, 201, 176));
        btnMenos.setText("-");
        btnMenos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 70));

        btnNueve.setBackground(new java.awt.Color(72, 201, 176));
        btnNueve.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnNueve.setForeground(new java.awt.Color(72, 201, 176));
        btnNueve.setText("9");
        btnNueve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        jPanel2.add(btnNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 100, 80));

        btnOcho.setBackground(new java.awt.Color(72, 201, 176));
        btnOcho.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnOcho.setForeground(new java.awt.Color(72, 201, 176));
        btnOcho.setText("8");
        btnOcho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        jPanel2.add(btnOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 80));

        btnSiete.setBackground(new java.awt.Color(72, 201, 176));
        btnSiete.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnSiete.setForeground(new java.awt.Color(72, 201, 176));
        btnSiete.setText("7");
        btnSiete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        jPanel2.add(btnSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 80));

        btnCuatro.setBackground(new java.awt.Color(72, 201, 176));
        btnCuatro.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnCuatro.setForeground(new java.awt.Color(72, 201, 176));
        btnCuatro.setText("4");
        btnCuatro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        jPanel2.add(btnCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 70));

        btnCinco.setBackground(new java.awt.Color(72, 201, 176));
        btnCinco.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnCinco.setForeground(new java.awt.Color(72, 201, 176));
        btnCinco.setText("5");
        btnCinco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, 70));

        btnSeis.setBackground(new java.awt.Color(72, 201, 176));
        btnSeis.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnSeis.setForeground(new java.awt.Color(72, 201, 176));
        btnSeis.setText("6");
        btnSeis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, 70));

        btnUno.setBackground(new java.awt.Color(72, 201, 176));
        btnUno.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnUno.setForeground(new java.awt.Color(72, 201, 176));
        btnUno.setText("1");
        btnUno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        jPanel2.add(btnUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 70));

        btnDos.setBackground(new java.awt.Color(72, 201, 176));
        btnDos.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnDos.setForeground(new java.awt.Color(72, 201, 176));
        btnDos.setText("2");
        btnDos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        jPanel2.add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 70));

        btnTres.setBackground(new java.awt.Color(72, 201, 176));
        btnTres.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnTres.setForeground(new java.awt.Color(72, 201, 176));
        btnTres.setText("3");
        btnTres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        jPanel2.add(btnTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 100, 70));

        btnparentesisuno.setBackground(new java.awt.Color(72, 201, 176));
        btnparentesisuno.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnparentesisuno.setForeground(new java.awt.Color(72, 201, 176));
        btnparentesisuno.setText("(");
        btnparentesisuno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnparentesisuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparentesisunoActionPerformed(evt);
            }
        });
        jPanel2.add(btnparentesisuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 80));

        btnCero.setBackground(new java.awt.Color(72, 201, 176));
        btnCero.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnCero.setForeground(new java.awt.Color(72, 201, 176));
        btnCero.setText("0");
        btnCero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        jPanel2.add(btnCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 90, 70));

        btnBorrar.setBackground(new java.awt.Color(72, 201, 176));
        btnBorrar.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(72, 201, 176));
        btnBorrar.setText("C");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 440, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        // TODO add your handling code here:
        addNumber("2");
         btnIgual.doClick();
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnParentesisdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesisdosActionPerformed
        // TODO add your handling code here:
        addNumber(")");
         btnIgual.doClick();
    }//GEN-LAST:event_btnParentesisdosActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtResultado.setText("");
        txtOperacion.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnparentesisunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparentesisunoActionPerformed
        // TODO add your handling code here:
        addNumber("(");
         btnIgual.doClick();
    }//GEN-LAST:event_btnparentesisunoActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        // TODO add your handling code here:
        addNumber("0");
         btnIgual.doClick();
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        addNumber(".");
         btnIgual.doClick();
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        // TODO add your handling code here:
        addNumber("1");
         btnIgual.doClick();
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        // TODO add your handling code here:
        addNumber("3");
         btnIgual.doClick();
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
        addNumber("-");
         btnIgual.doClick();
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        // TODO add your handling code here:
        addNumber("4");
         btnIgual.doClick();
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        // TODO add your handling code here:
        addNumber("5");
         btnIgual.doClick();
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        // TODO add your handling code here:
        addNumber("6");
         btnIgual.doClick();
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        addNumber("+");
         btnIgual.doClick();
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        // TODO add your handling code here:
        addNumber("7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        // TODO add your handling code here:
        addNumber("8");
         btnIgual.doClick();
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        // TODO add your handling code here:
        addNumber("9");
         btnIgual.doClick();
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        // TODO add your handling code here:
        addNumber("*");
         btnIgual.doClick();
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
        // TODO add your handling code here:
        addNumber("%");
         btnIgual.doClick();
    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        addNumber("/");
        btnIgual.doClick();
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
     try
     {
         String resultado = jvs.eval(txtOperacion.getText()).toString();
         txtResultado.setText(resultado);
     }
     catch(Exception e)
             {
                 
             }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.decode("#2E4053"));
        jPanel2.setBackground(Color.decode("#212F3C"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.decode("#F4FDFB"));
        jPanel2.setBackground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    
    public void addNumber(String digito)
    {
        txtOperacion.setText(txtOperacion.getText()+digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnParentesisdos;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnparentesisuno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
